version: '3.7'

services:
  database:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - PGDATA:/var/lib/postgresql/data
    env_file:
      - env.dev

  backend:
    build: .
    depends_on:
      - database
    env_file:
      - env.dev
    ports:
      - "8000:8000"
    volumes:
      - ./src:/discountcode

volumes:
  PGDATA:
